//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Planner_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewGymPlannerEntities : DbContext
    {
        public NewGymPlannerEntities()
            : base("name=NewGymPlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Days> Days { get; set; }
        public virtual DbSet<Exercises> Exercises { get; set; }
        public virtual DbSet<MuscleGroups> MuscleGroups { get; set; }
        public virtual DbSet<Sets> Sets { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Workouts> Workouts { get; set; }
    }
}
